# name: main
# ## Triggers the workflow on when there is a push, or 
# ## pull request on the main branch
# on: push 
# jobs:
#   job1:
#     ## The type of runner that the job will run on
#     runs-on: ubuntu-latest 
#     env:

#       ## Environment variable
#       API_KEY: XXXXXXXXXXXX    
#     steps:
#       - name: step 1
#         ## Reference your environment variables
#         # run: echo "The API key is:${{env.API_KEY}}"  
#         run: echo "The API key is:$API_KEY"  

#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step 1
#         ## Another way reference your environment variables
#         run: echo "The API key is:$API_KEY"   

# name: main

# on: push 

# env:

#       ## Environment variable define globally
#     Name: "aman" 
# jobs:
#   job1:
    
#     runs-on: ubuntu-latest 
     
#     steps:
#       - name: step 1
        
#         run: echo "The API key is:${{env.Name}}"  
        

#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step 1
      
#         run: echo "The API key is:$Name"

name: main

on: push 

env: |

      ## Environment variable define globally
    A: 1
    B: 5 
jobs:
  job1:
    
    runs-on: ubuntu-latest 
     
    steps:
      - name: step 1
        
        run: echo "The API key is:${{env.A + env.B}}"  
        

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
      
        run: echo "The API key is:${A+B}" 


# name: main
# ## Triggers the workflow on when there is a push, or 
# ## pull request on the main branch
# on: push 

# jobs:
#   job1:
#     ## The type of runner that the job will run on
#     runs-on: ubuntu-latest 
#     steps:
#       - name: step 1
#         env:
#           ## Environment variable for step 1
#           API_KEY: 2
#           API_KEY1: 3

#         ## Reference your environment variables
#         run: echo "The API key is:${{env.API_KEY+env.API_KEY1}}"   
#       - name: step 2
#         ## Reference your environment variables
#         run: echo "The API key is:${{env.API_KEY}}" 

# name: main

# on: push 
#   schedule:
#     - cron: '5 * * * *'
# jobs:
#   build:
#     name: Trigger Site Rebuild
#     runs-on: ubuntu-latest
#     env:

#       ## Environment variable
#       Name: "AMAN" 
#     steps:
        
#       - name: step 1
#         ## Another way reference your environment variables
#         run: echo "The API key is:$Name