# name: main
# ## Triggers the workflow on when there is a push, or 
# ## pull request on the main branch
# on: push 
# jobs:
#   job1:
#     ## The type of runner that the job will run on
#     runs-on: ubuntu-latest 
#     env:

#       ## Environment variable
#       API_KEY: XXXXXXXXXXXX    
#     steps:
#       - name: step 1
#         ## Reference your environment variables
#         # run: echo "The API key is:${{env.API_KEY}}"  
#         run: echo "The API key is:$API_KEY"  

#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step 1
#         ## Another way reference your environment variables
#         run: echo "The API key is:$API_KEY"   

# name: main

# on: push 

# env:

#       ## Environment variable define globally
#     Name: "aman" 
# jobs:
#   job1:
    
#     runs-on: ubuntu-latest 
     
#     steps:
#       - name: step 1
        
#         run: echo "The API key is:${{env.Name}}"  
        

#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step 1
      
#         run: echo "The API key is:$Name"

# name: main

# on: push 

# env: 

#       ## Environment variable define globally
#     name1: "aman"

#     name2: "suraj"  

#     number1: 55
#     number2: 12
# jobs:
#   job1:
    
#     runs-on: ubuntu-latest 
     
#     steps:
#       - name: step 1
        
#         run: echo "The name both are:$name1 $name2"  
        

#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step 1
      
#         run: echo "The both name are :${name1}" 


 

name: main

on: push 
  schedule:
    - cron: '5 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v1  
      - name: step 1
        ## Another way reference your environment variables
        run: echo "runing"


